# Generated by Django 6.0.4 on 2026-04-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_akku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ensayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
