# Generated by Django 6.0.4 on 2026-05-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_akku', '0002_cliente_estrategia_delete_curso_delete_prospecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
