# Generated by Django 6.0.4 on 2026-04-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_akku', '0002_ensayo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ensayo',
        ),
    ]
